lobby-time: 30
player-min: 75
players-by-team: 25
prepare-time: 600
game-time: 3600
wither-health: 1000
fortress-build-protection: 20
enable-compass: true
preparation-lock-container: true
always-day-lobby: true
always-day-game: true
allow-spectator: true
force-player-team: false
enable-bungeecord: false
bungeecord-lobby: lobby
player-death-lightning: true
max-build-height: 200
config-mode: true